### ISSUE TITLE
Linking not working

### ISSUE THREAD

**Issue by epetros** [citiususc/Linguakit#12]
Greetings,
The module for Entity linking is not working.

Regards

**Comment by gamallo** [comment]
Yes, there is a memory issue since this module requires too much memory. Now, we are trying to export the module to another server. As soon as we fix the problem, I'll send a message here. Thank you for the warning again and sorry for the new trouble.

**Comment by epetros** [comment]
Greetings,
Any progress on this issue? 
Thanks

**Comment by gamallo** [comment]
Hi, we're working on that. The software is already in the new server but it does not work yet. We're are debugging. Sorry for the delay

**Comment by gamallo** [comment]
The api services have been moved to another server. Now, the linking module is working.
Sorry for the delay.
Cheers
