### ISSUE TITLE
String MalFormed

### ISSUE THREAD

**Issue by crashangelbr** [citiususc/Linguakit#13]
Hi, i receive this error when use words acents...

`linguakit dep -fa pt "está" -s

`utf8 "\xE1" does not map to Unicode at c:\Linguakit\\linguakit.perl line 228, <$input> line 1.
Malformed UTF-8 character (unexpected end of string) in substitution (s///) at c:\Linguakit/tagger/pt/sentences-pt_exe.perl line 61, <$input> line 1.`

**Comment by gamallo** [comment]
Hi, I think that the input is not in utf8 but probably in iso-8859-1. You should change the encoding of your command line into utf8. Otherwise, you can use as input a file saved in utf8 and then run the syntactic analyzer as follows:

cat input_file.txt | ./linguakit dep pt -fa 

Cheers!
