### ISSUE TITLE
Issue in sentiment score calculation

### ISSUE THREAD

**Issue by SeenaLibin** [citiususc/Linguakit#5]
Hi,
I used sentiment analyzer provided at the live demo site and also tested with github code. I found a lot of difference with the sentiment score. Why is it so? Can you help me out of this Please?

**Comment by gamallo** [comment]
Hi,
The main difference is that the sentiment analysis module uses different PoS taggers in the two versions: in the live demo it uses Freeling while in github the PoS tagger is ours.
I also found another small difference concerning encoding but in the last version of the github code I fixed it.  Please, update your github code with the last version of Linguakit and check the new version of the sentiment analysis module. Thanks!!

**Comment by SeenaLibin** [comment]
Ok..  So how can I get the same accuracy in sentiment percentage calculation as in live demo with in my github cloned version

**Comment by gamallo** [comment]
This is not trivial at all. To do that, you should use as input of the sentiment analysis module the same version of FreeLing (3.0, I think) as that used by the live demo. Sorry.
