### ISSUE TITLE
Issue with Summarizer

### ISSUE THREAD

**Issue by epetros** [citiususc/Linguakit#8]
Greetings,
Unfortunately the summarizer module is not working.
Thanks

**Comment by gamallo** [comment]
That's a problem with the server. It's fixed. Thanks for the warning.

**Comment by epetros** [comment]
Thanks.

**Comment by epetros** [comment]
Greetings,
The summarizer module is off again.
Thanks

**Comment by gamallo** [comment]
It was off because of the storm last night. It is working again. Thanks for warning us!

**Comment by epetros** [comment]
Sorry, but its off again.

**Comment by gamallo** [comment]
It is working again. I don't know why it was off. Sorry

**Comment by epetros** [comment]
Greetings, the server is down again for a while now...

**Comment by gamallo** [comment]
The log file reports a problem with the Web extractor. I think I fixed the problem but I'm not pretty sure. 
The server is running again... Thanks for the warning.

**Comment by epetros** [comment]
Unfortunatly still not working...

**Comment by epetros** [comment]
Unfortunatly still not working...

**Comment by gamallo** [comment]
I don't know what is happening. Now it is up

**Comment by epetros** [comment]
Greetings, unfortunately the server is down again..

**Comment by epetros** [comment]
Greetings, unfortunately the server is down again..

**Comment by gamallo** [comment]
Sorry. This time the problem was just the power and the SAI supporting the server. Now, it is running again.

**Comment by epetros** [comment]
Hello, sorry I just tested and unfortunately it's still down.

**Comment by epetros** [comment]
Greetings, unfortunately the server seems to be down most of the time.

**Comment by gamallo** [comment]
Sorry. I think there is a problem with the software used to create the web service: Dancer. I don't know how to fix the problem. I'll try to reinstall this software.

**Comment by ambs** [comment]
Hmms, usually Dancer is not a problem. I have a dozen websites running on it. I would guess on some other issue :)

**Comment by gamallo** [comment]
Thanks, Alberto. The error messages come from Dancer/Request.pm, but the problem could be before. Another solution is to put the summarizer in the package to be installed off-line. I don't remember why is just accessed via API.

**Comment by gamallo** [comment]
Thanks, Alberto. The error messages come from Dancer/Request.pm, but the problem could be before. Another solution is to put the summarizer in the package to be installed off-line. I don't remember why is just accessed via API.

**Comment by gamallo** [comment]
Hi, the source code of the summarizer has been uploaded. In the updated version of Linguakit the summarizer module does not require the API REST.  Let me know if this solves the problem. Thank you.

**Comment by epetros** [comment]
Greetings. Unfortunately for the new version am getting this error:
./lexicon_compiler.perl
Compiling lexicons:
        English         Done
        Portuguese      Out of memory!

**Comment by gamallo** [comment]
Hi, epetros. No changes have been done in the lexicons. I've just tried now to compile the new version and had no problems. I checked the RAM memory required to compile the portuguese dictionary: my laptop uses 3% out of the total memory (8G). Try to compile again by closing before all the open applications in your computer.

**Comment by epetros** [comment]
Managed to have it working, thanks!
